name: Deploy Garbage Tracking

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: admin123
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            cd ~/garbage_tracking
            git reset --hard
            git pull origin main
            source ~/garbage_tracking/garbage_venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart garbage_tracking
