name: Deploy to Local Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: "192.168.1.100"      # <-- apne server ka LAN IP daalna
          username: "admin123"       # <-- tumhara server ka user
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/garbage_tracking
            git pull origin main
            pkill -f streamlit || true
            nohup streamlit run app.py --server.port 8501 --server.address 0.0.0.0 &
