name: Deploy Garbage Tracking

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/garbage_tracking

            # virtual env activate
            source ~/garbage_tracking/garbage_venv/bin/activate

            # dependencies update
            pip install -r requirements.txt

            # kill only garbage_tracking streamlit process
            pkill -f "streamlit run app.py --server.port 8501" || true

            # run again in background
            nohup streamlit run app.py --server.port 8501 > ~/garbage_tracking.log 2>&1 &
