name: Deploy Garbage Tracking App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/admin123/garbage_tracking
            echo "🔄 Pulling latest changes..."
            git reset --hard
            git pull origin main

            echo "📦 Installing dependencies..."
            /home/admin123/garbage_tracking/garbage_venv/bin/pip install -r requirements.txt

            echo "🚀 Restarting service..."
            sudo systemctl restart garbage_tracking
            sudo systemctl status garbage_tracking --no-pager -l
            echo "✅ Deployment completed successfully!"